### ISSUE TITLE
generator error with sails 0.12

### ISSUE THREAD

**Issue by JerryYangJin** [langateam/sails-permissions#223]
Hello, the generator is not working for me with sails 0.12 on windows 32-bit, i found a (workaround)[#222], if i followed the workaround, the generator will not throw any error, but only generate `config/permissions.js`

```sh
>npm -v
2.14.12
>node -v
v4.3.1
>sails -v
0.12.1
```

```sh
>sails generate permissions-api
error: Error in "permissions-api" generator (loaded from sails-permissions/gener
ator)
C:\Users\AppData\Roaming\npm\node_modules\sails\node_modules\sails-generat
e\lib\index.js:51
      throw e;
      ^

Error: Cannot find module 'C:\Users\sails-permissions\generato
r'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\AppData\Roaming\npm\node_modules\sails\nod
e_modules\sails-generate\lib\index.js:71:19)
    at Command.module.exports (C:\Users\AppData\Roaming\npm\node_modules\s
ails\bin\sails-generate.js:107:10)
    at Command.listener (C:\Users\AppData\Roaming\npm\node_modules\sails\n
ode_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\AppData\Roaming\npm\node_modules\sails\
node_modules\commander\index.js:615:12)
```

**Comment by oca159** [comment]
I have the same error, could you please tell me what is your workaround?

**Comment by GeeWee** [comment]
Having same issue.

**Comment by openmynet** [comment]
workaround: 
```
{
  "generators": {
    "modules": {
      "permissions-api": "node_modules/sails-permissions/generator"
    }
  }
}
```

**Comment by lakinoheat** [comment]
Try changing the .sailsrc as follows:
{
  "generators": {
    "modules": {
      "permissions-api": "**node_modules/**sails-permissions/generator"
    }
  }
}
